steps:
- name: 'Install Terraform'
  image: 'hashicorp/terraform:latest'
  script: |
    terraform init

- name: 'Plan Terraform Changes'
  image: 'hashicorp/terraform:latest'
  script: |
    terraform plan
  working-directory: ./gcp_web_app/infra_app

- name: 'Apply Terraform Changes'
  image: 'hashicorp/terraform:latest'
  script: |
    terraform apply -auto-approve
  working-directory: ./gcp_web_app/infra_app
