steps:
- name: 'Install Terraform'
  script: |
    wget -q -O - https://releases.hashicorp.com/terraform/latest/terraform_$(uname -s)_$(uname -m) -O terraform
    chmod +x terraform
  dir: ./gcp_web_app/infra_app

- name: 'Initialize Terraform'
  script: |
    terraform init
  dir: ./gcp_web_app/infra_app

- name: 'Plan Terraform Changes'
  script: |
    terraform plan
  dir: ./gcp_web_app/infra_app

- name: 'Apply Terraform Changes'
  script: |
    terraform apply -auto-approve
  dir: ./gcp_web_app/infra_app
