steps:
- name: 'Install Terraform'
  script: |
    wget -q -O - https://releases.hashicorp.com/terraform/latest/terraform_$(uname -s)_$(uname -m) -O terraform
    chmod +x terraform
  working-directory: ./gcp_web_app/infra_app

- name: 'Initialize Terraform'
  script: |
    terraform init
  working-directory: ./gcp_web_app/infra_app

- name: 'Plan Terraform Changes'
  script: |
    terraform plan -var="project_id=your-project-id" -var="region=your-region"
  working-directory: ./gcp_web_app/infra_app

- name: 'Apply Terraform Changes'
  script: |
    terraform apply -auto-approve -var="project_id=your-project-id" -var="region=your-region"
  working-directory: ./gcp_web_app/infra_app
