name: Terraform GCP Workflow

on:
  push:
    branches:
      - main  # Change this to your default branch

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}  # Your GCP project ID
          service_account_key: ${{ secrets.GCP_SA_KEY }}  # Base64 encoded service account key
          export_default_credentials: true  # Export the credentials for later use

      - name: Install Terraform
        run: |
          echo "Installing Terraform..."
          TERRAFORM_VERSION=$(curl -s https://releases.hashicorp.com/terraform/ | grep -oP 'terraform_\K[0-9.]+(?=</a>)' | head -1)
          wget -q -O terraform.zip https://releases.hashicorp.com/terraform/$TERRAFORM_VERSION/terraform_$TERRAFORM_VERSION_linux_amd64.zip
          unzip terraform.zip
          sudo mv terraform /usr/local/bin/
          terraform -version

      - name: Terraform Init
        run: |
          echo "Initializing Terraform..."
          cd infra  # Change to the infra directory
          terraform init

      - name: Terraform Plan
        run: |
          echo "Planning Terraform changes..."
          cd infra  # Change to the infra directory
          terraform plan
